### ISSUE TITLE
Release & publish on hackage

### ISSUE THREAD

**Issue by volhovM** [input-output-hk/pvss-haskell#6]
Subj. Can it be done?

**Comment by vincenthz** [comment]
Now that the repo is public, I don't see a reason why not, but I'm not sure I should make the call about these things or if it need special consideration about license, copyrights, etc..

**Comment by volhovM** [comment]
Do we have any progress with this issue? It's somewhat problematic/inconvenient to package any piece of haskell software with nix until library gets to hackage and then to nixpkgs (they are synchronized). We workaround this on deployment by using custom build for now.

**Comment by vincenthz** [comment]
this is now on hackage as 'pvss'
