### ISSUE TITLE
Instance Binary KeyPair

### ISSUE THREAD

**Issue by gromakovsky** [input-output-hk/pvss-haskell#7]
Can it be added? It may be useful to store key on disk, for example.

**Comment by vincenthz** [comment]
I've added a binary instance, but also to add that the private key is enough to derive the public part.

**Comment by gromakovsky** [comment]
Alright, I see. Apparently I just missed moment when `PrivateKey` newtype has been added.

**Comment by vincenthz** [comment]
I suppose it depends if you prefer to optimise the storage (32 bytes vs 65 bytes), or the (small) cpu overhead of recalculating a key. Let me know if you prefer to optimise storage, I can recalculate the public key in the binary instance.
