### ISSUE TITLE
Meta-data issues with pvss-0.1

### ISSUE THREAD

**Issue by hvr** [input-output-hk/pvss-haskell#9]
I noticed your recent package upload to Hackage as it was flagged by the matrix buildbot due to  packaging meta-data issues:

- The `description` ("Please see README.md") is not a proper description for your package (and Hackage will show a link to the README at the end of the description *if* the README exists; therefore that phrase is redundant), and hence this will cause poor experience for users (NB: your package won't be properly indexed by Hackage's package search feature and thus hurt its discoverability). See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more details.

- The build-dependencies have inaccurate versions bounds. Please be aware that accurate version bounds are mandated by the [PVP](http://pvp.haskell.org/), and adherence to the PVP is expected as part of the Hackage guidelines.  This has various knock off consequences, such as Hackage possibly not being able to generate Haddock documentation for your package, install-plans degrading over time, as well generally resulting in a poor experience for users since they'll run into the same compilation errors.

The `cabal gen-bounds` command can be used to help infer an initial set of version bounds, see  [Cabal User Guide | Generating dependency version bounds](http://cabal.readthedocs.io/en/latest/developing-packages.html#generating-dependency-version-bounds) for more details.

 Specifically, I've noticed the following compile error

```
Configuring component lib from pvss-0.1
Preprocessing library pvss-0.1...

src/Crypto/PVSS.hs:8:12:
    unknown flag in  {-# OPTIONS_GHC #-} pragma: -Wno-unused-top-binds

src/Crypto/PVSS.hs:9:12:
    unknown flag in  {-# OPTIONS_GHC #-} pragma: -Wno-name-shadowing

src/Crypto/PVSS.hs:10:12:
    unknown flag in  {-# OPTIONS_GHC #-} pragma: -Wno-unused-matches
cabal: Failed to build pvss-0.1 (which is required by exe:pvss-exe from
pvss-0.1).
```

If you have any questions, please let me know!

**Comment by vincenthz** [comment]
PvP spam

**Comment by hvr** [comment]
@vincenthz I'm sorry you feel that way. One way to avoid being informed about problems with your package uploads would be to not upload them to Hackage, then they won't be flagged.
